spring:
  application:
    name: login-fileUpload-code

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/sky_take_out

# mybatis??
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    ????
    map-underscore-to-camel-case: true

# ??????????
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug



